name: Build

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - package.json
      - vite.config.ts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Get package version
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f dist/*
          git diff --staged --quiet || git commit -m "🔧 Automated build: v${{ steps.package_version.outputs.version }}" && git push
